jantman/awslimitchecker

- .coveragerc
- .landscape.yaml
- .travis.yml
- CHANGES.rst
- README.rst
- awslimitchecker/checker.py
- awslimitchecker/runner.py
- awslimitchecker/tests/test_checker.py
- awslimitchecker/tests/test_runner.py
- awslimitchecker/tests/test_utils.py
- awslimitchecker/tests/test_version.py
- awslimitchecker/tests/test_versioncheck.py
- awslimitchecker/utils.py
- awslimitchecker/version.py
- awslimitchecker/versioncheck.py
- docs/source/awslimitchecker.rst
- docs/source/awslimitchecker.versioncheck.rst
- docs/source/cli_usage.rst
- docs/source/conf.py
- docs/source/development.rst
- docs/source/index.rst
- pytest.ini
- setup.py
- tox.ini
This fixes #44 - 0.1.0 release
> 0.1.0 release

- .travis.yml
- CHANGES.rst
- awslimitchecker/services/autoscaling.py
- awslimitchecker/services/base.py
- awslimitchecker/services/ebs.py
- awslimitchecker/services/ec2.py
- awslimitchecker/services/elasticache.py
- awslimitchecker/services/elb.py
- awslimitchecker/services/newservice.py.example
- awslimitchecker/services/rds.py
- awslimitchecker/services/vpc.py
- awslimitchecker/tests/services/test_autoscaling.py
- awslimitchecker/tests/services/test_ebs.py
- awslimitchecker/tests/services/test_ec2.py
- awslimitchecker/tests/services/test_elasticache.py
- awslimitchecker/tests/services/test_elb.py
- awslimitchecker/tests/services/test_newservice.py.example
- awslimitchecker/tests/services/test_rds.py
- awslimitchecker/tests/services/test_vpc.py
- awslimitchecker/tests/test_trustedadvisor.py
- awslimitchecker/tests/test_utils.py
- awslimitchecker/tests/test_versioncheck.py
- awslimitchecker/trustedadvisor.py
- awslimitchecker/utils.py
- awslimitchecker/versioncheck.py
- docs/source/development.rst
- docs/source/internals.rst
- tox.ini
This adds handling for pagination of API responses.
* Queries that return a ``boto.resultset.ResultSet`` object are paginated automatically.
* Queries that return a dict need some additional kwargs to power the pagination
> Fixes #40 - pagination of API responses

- awslimitchecker/checker.py
- awslimitchecker/connectable.py
- awslimitchecker/runner.py
- awslimitchecker/services/base.py
- awslimitchecker/tests/test_checker.py
- awslimitchecker/tests/test_connectable.py
- awslimitchecker/tests/test_runner.py
- awslimitchecker/tests/test_trustedadvisor.py
- awslimitchecker/trustedadvisor.py
- docs/source/cli_usage.rst
Support MFA device for cross account role switching, reusing STS credentials between API calls as MFA Token cannot be used more than once.
This introduces two new optional command line arguments:
-M MFA_SERIAL_NUMBER, --mfa-serial-number MFA_SERIAL_NUMBER
MFA Serial Number to use when assuming a role via STS
-T MFA_TOKEN, --mfa-token MFA_TOKEN
MFA Token to use when assuming a role via STS
> Support MFA device for cross account role switching

- .travis.yml
- CHANGES.rst
This re-enables py35 on TravisCI. This does increase build time - as far as I can tell, by up to 25% - but it's the only way I can figured out to get py35 working, since it's currently an on-demand installation in Travis, and there doesn't seem to be a clear way to install it myself at runtime.
> Issues/117 - re-enable py35 tests

- CHANGES.rst
- awslimitchecker/services/ec2.py
- awslimitchecker/tests/services/test_ec2.py
- add t2.nano EC2 instance type
- fix typo - "m4.8xlarge" should have been "m4.10xlarge"
- update default limits for m4.(4|10)xlarge
> Issues/116 - fix EC2 instance types

- .travis.yml
explicitly specify the python version for each build, so we're sure it's installed, but we're not uselessly installing recent versions for builds that don't use them
> issue #117 - explicitly specify python version for each build in Travis

- .travis.yml
- README.rst
- docs/source/development.rst
- docs/source/getting_started.rst
- docs/source/index.rst
Remove PyPy and PyPy3 testing, and drop -versioncheck to just py27 and py35
> Issues/166 - reduce Travis test time

- awslimitchecker/services/ec2.py
- docs/source/cli_usage.rst
- docs/source/limits.rst
This limit was increased from 100 to 500 at some point, though I'm not sure exactly when. http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Appendix_Limits.html#vpc-limits-security-groups
* I have the …
> Update security group per VPC default limit to 500

- CHANGES.rst
- awslimitchecker/services/vpc.py
- awslimitchecker/tests/services/test_vpc.py
- awslimitchecker/tests/support.py
- docs/source/cli_usage.rst
- docs/source/development.rst
- docs/source/iam_policy.rst
- docs/source/limits.rst
* update docs
* add ec2:DescribeNatGateways permission to VPC
* handle regions that don't have NAT Gateway Service, causing boto to throw a ClientError:
```
ClientError: An error occurred (AuthFailure) when calling the DescribeNatGateways operation: This request has been administratively disabled.
```
> Fixes for NAT Gateways

- CHANGES.rst
- awslimitchecker/services/ec2.py
- awslimitchecker/tests/services/test_ec2.py
- docs/source/limits.rst
Adds support for some missing instance types:
* ``m4.16xlarge``
* ``x1.16xlarge``
* ``x1.32xlarge``
* ``p2.xlarge``
* ``p2.8xlarge``
* ``p2.16xlarge``
> fixes #217 - add support for some new/missing instance types

- CHANGES.rst
- awslimitchecker/services/ec2.py
- awslimitchecker/tests/services/result_fixtures.py
for 'Regional Benefit' AZ-less Reserved Instances, don't die with a KeyError but don't subtract them from On-Demand either; just log a debug message
I may need to come back and fix this, if they should really be subtracted from the On-Demand count.
> issue #215 - don't die on AZ-less EC2 reserved instances

- CHANGES.rst
- awslimitchecker/services/ec2.py
- awslimitchecker/tests/services/result_fixtures.py
- awslimitchecker/tests/services/test_ec2.py
Fixes #215
The fact that Regional Benefit (AZ-less) RIs don't count against on-demand usage was confirmed for me by AWS Support.
> fixes #215 - subtract AZ-less 'Regional Benefit' RIs from usage

- awslimitchecker/services/__init__.py
- awslimitchecker/services/firehose.py
- awslimitchecker/tests/services/result_fixtures.py
- awslimitchecker/tests/services/test_firehose.py
- docs/source/awslimitchecker.services.rst
- docs/source/limits.rst
This pull request creates the service Firehose and implements the metric "'Delivery streams per region".
More information on this limit:
- http://docs.aws.amazon.com/firehose/latest/dev/limits.html
- http://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits-akf
---
**IMPORTANT:** Please take note of the below checklist, especially the first two items.
`connect()` and `connect_resource()` methods, inherited from …
> Add support to Kinesis Firehose delivery streams metric

- awslimitchecker/services/elasticache.py
Ref: #241 
``-versioncheck`` tox tests.
or any subsequent version of …
> issue #241 - increase default ElastiCache/Nodes limit from 50 to 100

- awslimitchecker/checker.py
- awslimitchecker/runner.py
- awslimitchecker/tests/test_checker.py
- awslimitchecker/tests/test_runner.py
Allows the `--service` argument to accept multiple values.
> Accept multiple services.

- awslimitchecker/services/ec2.py
- awslimitchecker/tests/services/result_fixtures.py
- awslimitchecker/tests/services/test_ec2.py
Handle govcloud-specific edge cases.
* Handle errors on spot instance and fleet requests
* Handle false zero limit on EIP
> Handle govcloud-specific edge cases.

- .travis.yml
- CHANGES.rst
- README.rst
- awslimitchecker/checker.py
- awslimitchecker/runner.py
- awslimitchecker/tests/test_checker.py
- awslimitchecker/tests/test_version.py
- awslimitchecker/version.py
- docs/source/getting_started.rst
- setup.py
- tox.ini
This drops support and testing for py32, per #236
> fixes #236 - drop py32 support and testing

- CHANGES.rst
- awslimitchecker/services/elasticache.py
- awslimitchecker/tests/services/result_fixtures.py
- awslimitchecker/tests/services/test_elasticache.py
handle case where ElastiCache DescribeCacheClusters result for a cluster is missing CacheNodes key
Fixes #257
> fixes #257 - CacheNodes key missing

- CHANGES.rst
- awslimitchecker/services/ec2.py
- awslimitchecker/tests/services/test_ec2.py
- docs/build_generated_docs.py
- docs/source/cli_usage.rst
- docs/source/limits.rst
Fixes #200 - EC2 Spot Instance support has been live for 4+ months. Removing from experimental status.
> fixes #200 - remove EC2 Spot Instance support from experimental status

- awslimitchecker/checker.py
- awslimitchecker/runner.py
- awslimitchecker/tests/test_runner.py
1) `tox -e docs` was producing non-useful diffs.
2) Please suggest a better test?
3) I'll be the first to admit, the method used to disable services is slightly unconventional, but I believe the approach employed results in the least number of changed lines of code.
this pull request grants a perpetual, global, unlimited license for it to be used and …
> add new flag: --skip-service

- awslimitchecker/services/__init__.py
- awslimitchecker/services/efs.py
- awslimitchecker/tests/services/test_efs.py
- docs/source/awslimitchecker.services.efs.rst
- docs/source/awslimitchecker.services.rst
or any subsequent version of that license if adopted by …
> Add AWS::EFS::FileSystem limit check.

- .gitignore
- CHANGES.rst
- awslimitchecker/services/elb.py
- awslimitchecker/tests/services/result_fixtures.py
- awslimitchecker/tests/services/test_elb.py
Fixes #268 - ALB limits and (A|E)LB limit values from API.
> fixes #268 - add support for ALB limits, and get ELB limits from API

- CHANGES.rst
- awslimitchecker/services/vpc.py
- awslimitchecker/tests/services/result_fixtures.py
- awslimitchecker/tests/services/test_vpc.py
Fixes #294 - ignore [NAT Gateways](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_NatGateway.html) not in "available" or "pending" state (i.e. ignore ones that have a State of ``failed | deleting | deleted``).
> Fixes #294 - ignore failed/deleted NAT Gateways

- CHANGES.rst
- awslimitchecker/checker.py
- awslimitchecker/runner.py
- awslimitchecker/tests/test_checker.py
- awslimitchecker/tests/test_runner.py
- awslimitchecker/tests/test_utils.py
- awslimitchecker/utils.py
- awslimitchecker/version.py
Checks PyPI for latest version, logs a warning if a newer version is available. Has a 4-second timeout and can be disabled.
> Fixes #253 - latest version check

- awslimitchecker/services/vpc.py
- awslimitchecker/tests/services/result_fixtures.py
- awslimitchecker/tests/services/test_vpc.py
- docs/source/limits.rst
__IMPORTANT:__ Please take note of the below checklist, especially the first two items.
the issue is …
> Add ability to describe virtual private gateways

- CHANGES.rst
- awslimitchecker/services/__init__.py
- awslimitchecker/services/base.py
- awslimitchecker/services/dynamodb.py
- awslimitchecker/tests/services/result_fixtures.py
- awslimitchecker/tests/services/test_dynamodb.py
- awslimitchecker/tests/test_checker.py
- docs/source/awslimitchecker.services.dynamodb.rst
- docs/source/awslimitchecker.services.rst
__IMPORTANT:__ Please take note of the below checklist, especially the first two items.
the issue is …
> DynamoDB support

- README.rst
[`describe_account_limits`](https://github.com/jantman/awslimitchecker/blob/master/awslimitchecker/services/elb.py#L253) for  `AWS::ElasticLoadBalancing::LoadBalancer` requires boto3 >= 1.4.4. It would be helpful to update the README accordingly. Thanks!
> Update README to require boto3 >= 1.4.4

- CHANGES.rst
- README.rst
- awslimitchecker/services/ec2.py
- awslimitchecker/tests/services/test_ec2.py
- awslimitchecker/version.py
- docs/source/getting_started.rst
- docs/source/limits.rst
- setup.py
2.0.0 release.
There aren't many changes, but per our versioning policy, bumping the boto3 requirement from 1.2.3 to 1.4.4 requires a major version bump.
> Issues/311 - 2.0.0 release

- CHANGES.rst
- awslimitchecker/services/autoscaling.py
- awslimitchecker/services/ebs.py
- awslimitchecker/services/elasticbeanstalk.py
- awslimitchecker/services/iam.py
- awslimitchecker/tests/services/test_ebs.py
Updates values to reflect AWS default limits for Elastic Beanstalk, Autoscaling, EBS and IAM
https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html#limits_elastic_beanstalk …
> Update Elastic Beanstalk default values

- CHANGES.rst
- awslimitchecker/tests/test_trustedadvisor.py
- awslimitchecker/trustedadvisor.py
handle checks with status not_available or missing flaggedResources key
> fixes #337 - handle Trusted Advisor broken checks

- CHANGES.rst
- awslimitchecker/limit.py
- awslimitchecker/runner.py
- awslimitchecker/services/__init__.py
- awslimitchecker/services/route53.py
- awslimitchecker/tests/services/result_fixtures.py
- awslimitchecker/tests/services/test_route53.py
- awslimitchecker/tests/support.py
- awslimitchecker/tests/test_limit.py
- awslimitchecker/tests/test_runner.py
- docs/build_generated_docs.py
- docs/source/awslimitchecker.services.route53.rst
- docs/source/awslimitchecker.services.rst
- docs/source/cli_usage.rst
- docs/source/conf.py
- docs/source/development.rst
- docs/source/iam_policy.rst
- docs/source/limits.rst
This adds support to HostedZone limits. The ones in this request: https://docs.aws.amazon.com/Route53/latest/APIReference/API_GetHostedZoneLimit.html
By submitting this work for inclusion …
> Route53 HostedZone metrics

- docs/build_generated_docs.py
Fixes #346 - add documentation on side-effect API calls made by AWS services
> Fixes #346 - add documentation on side-effect API calls made by AWS services

- CHANGES.rst
- awslimitchecker/services/__init__.py
- awslimitchecker/services/cloudtrail.py
- awslimitchecker/tests/services/result_fixtures.py
- awslimitchecker/tests/services/test_cloudtrail.py
- awslimitchecker/tests/services/test_dynamodb.py
- docs/source/awslimitchecker.services.cloudtrail.rst
- docs/source/awslimitchecker.services.rst
Added support for CloudTrails service
[awslimitchecker.connectable.Connectable](http://awslimitchecker.readthedocs.org/en/latest/awslimi …
> CloudTrails service support

- .gitignore
- CHANGES.rst
- awslimitchecker/limit.py
- awslimitchecker/services/__init__.py
- awslimitchecker/services/lambdafunc.py
- awslimitchecker/tests/services/result_fixtures.py
- awslimitchecker/tests/services/test_lambdafunc.py
- docs/build_generated_docs.py
- docs/source/awslimitchecker.services.lambdafunc.rst
- docs/source/awslimitchecker.services.rst
- docs/source/cli_usage.rst
- docs/source/iam_policy.rst
- docs/source/limits.rst
Adds support for AWS Lambda service, using this AWS API call response (`aws lambda get-account-settings`):
```
{
"AccountLimit": {
"CodeSizeUnzipped": 262144000, 
"UnreservedConcurrentExecutions": 1000, 
"ConcurrentExecutions": 1000, 
"CodeSizeZipped": 52428800, 
"TotalCodeSize": 80530636800
}, 
"AccountUsage": {
"FunctionCount": 12, 
"TotalCodeSize": 2167198
}
}
```
In the code base of awslimitchecker, usages and limits are treated equally. However, this is not true for AWS API in regards of the AWS Lambda service. Therefore, I've been coding it in the Lambda Service class to handle this, returning back different limits and usage metric points depending if you issue the -l or -u parameter upon execution of awslimitchecker. This may or maynot pass PR/code review, and I'm happy to oblige …
> Introducing AWS Lambda Limits and Usage

- CHANGES.rst
- awslimitchecker/services/apigateway.py
- awslimitchecker/tests/services/result_fixtures.py
- awslimitchecker/tests/services/test_apigateway.py
- docs/source/limits.rst
This PR fixes the API Gateway limits:
* ``ApiGateway`` service now has three ReST API limits (``Regional API keys per account``, ``Private API keys per account``, and ``Edge API keys per account``) in place of the previous single ``APIs per account`` to reflect the current documented service limits.
* API Gateway service - add support for ``VPC Links per account`` limit.
> Issues/365 - API Gateway limit updates

- CHANGES.rst
- awslimitchecker/services/elb.py
- awslimitchecker/tests/services/result_fixtures.py
- awslimitchecker/tests/services/test_elb.py
This adds support for the NLB limits and some missing ALB and Classic ELB limits, specifically:
* Add support for Network Load Balancer limits ``Network load balancers`` and ``Listeners per network load balancer``.
* Add support for Application Load Balancer limits ``Certificates per application load balancer``.
* Add support for Classic ELB (ELBv1) ``Registered instances per load balancer`` limit
There were some limits mentioned in #334 by @vhartikainen that are available in the DescribeAccountLimits API call that I've left out, specifically Targets per ALB, Targets per NLB, and Targets per Target Group. These limits default to 1000, 500, and 1000, respectively. Because of how the API works calculating usage for these limits would require a ``DescribeTargetHealth`` call for every Target …
> Issues/334 - ALB and NLB limits

- awslimitchecker/services/vpc.py
- awslimitchecker/tests/services/result_fixtures.py
- awslimitchecker/tests/services/test_vpc.py
This PR adds the `Network interfaces per Region` limit. This limit is described [here](https://docs.aws.amazon.com/vpc/latest/userguide/amazon-vpc-limits.html) is a bit unusual because the default is:
>This limit is the greater of either the default limit (350) or your On-Demand Instance limit multiplied by 5. 
I used 350 because that is the initial limit a new account will have, given that the default limit for On-Demand Instances is 20.
I had some trouble getting the docs to build so I did not complete that step (it is the only failure in travis). Sorry about that!
include complete test coverage will usually be …
> Add Network interfaces per Region limit

- awslimitchecker/services/dynamodb.py
- awslimitchecker/services/efs.py
- awslimitchecker/tests/services/test_dynamodb.py
- awslimitchecker/tests/services/test_efs.py
Update DynamoDB and EFS limits
More info on the issue : https://github.com/jantman/awslimitchecker/issues/390
> Update DynamoDB and EFS limits #390

- CHANGES.rst
- awslimitchecker/services/dynamodb.py
- awslimitchecker/services/efs.py
- awslimitchecker/tests/services/test_dynamodb.py
- awslimitchecker/tests/services/test_efs.py
- awslimitchecker/version.py
- docs/source/limits.rst
> fixes #392 - 6.1.3 release

- awslimitchecker/services/vpc.py
- awslimitchecker/tests/services/test_vpc.py
Fixes calculation for VPC Network Interface limit.
> Fix calculation of VPC Network Interfaces limit

- awslimitchecker/runner.py
- awslimitchecker/tests/test_runner.py
- docs/source/cli_usage.rst
- docs/source/cli_usage.rst.template
This PR adds support for skipping the result of specific checks. See #307 for more details.
```
ddelnano@10-81-17-110-uswest2adevc:~$ BOTO_CONFIG=/etc/boto_cfg/resource-limit-monitor.cfg awslimitchecker --ta-refresh-wait --no-check-version -r us-west-2 -S EC2 -L 'EC2/Running On-Demand c5.9xlarge instances'=2000 -L 'EC2/Running On-Demand i3.large instances'=16 -L 'EC2/Running On-Demand i3.xlarge instances'=50 -L 'EC2/Running On-Demand …
```
> Add support for ignoring specific checks based on service and check name

- awslimitchecker/services/elb.py
- awslimitchecker/tests/services/test_elb.py
- docs/examples/check_aws_limits.py
- docs/examples/multi-region_multi-account/config/111111111111/us-east-1/limit_overrides.json
- docs/source/limits.rst
This PR adds support for limits for ALBs and Classic LBs are now provided separately. See #412 for more details. …
> NOFORN - Limits for ALBs and Classic LBs are now provided separately

- CHANGES.rst
- awslimitchecker/runner.py
- awslimitchecker/tests/test_runner.py
- docs/build_generated_docs.py
- docs/source/cli_usage.rst
- docs/source/cli_usage.rst.template
- docs/source/iam_policy.rst
This PR adds support for command line arguments to set limit overrides and per-limit threshold overrides from a JSON file either on the local filesystem or dynamically retrieved from S3.
This essentially exposes the existing, formerly Python-API-only [awslimitchecker.checker.AwsLimitChecker.set_limit_overrides](https://awslimitchecker.readthedocs.io/en/latest/awslimitchecker.checker.html#awslimitchecker.checker.AwsLimitChecker.set_limit_overrides) and [awslimitchecker.checker.AwsLimitChecker.set_threshold_overrides](https://awslimitchecker.readthedocs.io/en/latest/awslimitchecker.checker.html#awslimitchecker.checker.AwsLimitChecker.set_threshold_overrides) methods via new ``--limit-override-json`` and ``--threshold-override-json`` command line options, which take either a local file path …
> Issue #324 - support setting limit and threshold overrides from local or S3 JSON file

- README.rst
- awslimitchecker/checker.py
- awslimitchecker/metrics/__init__.py
- awslimitchecker/metrics/base.py
- awslimitchecker/metrics/datadog.py
- awslimitchecker/metrics/dummy.py
- awslimitchecker/runner.py
- awslimitchecker/tests/metrics/__init__.py
- awslimitchecker/tests/metrics/test_base.py
- awslimitchecker/tests/metrics/test_datadog.py
- awslimitchecker/tests/metrics/test_dummy.py
- awslimitchecker/tests/test_checker.py
- awslimitchecker/tests/test_runner.py
- docs/build_generated_docs.py
- docs/source/awslimitchecker.metrics.base.rst
- docs/source/awslimitchecker.metrics.datadog.rst
- docs/source/awslimitchecker.metrics.dummy.rst
- docs/source/awslimitchecker.metrics.rst
- docs/source/awslimitchecker.rst
- docs/source/cli_usage.rst
- docs/source/cli_usage.rst.template
- docs/source/development.rst
- docs/source/getting_started.rst
- docs/source/iam_policy.rst
- pytest.ini
This PR implements the metrics provider subsystem described in #418, as well as the first two metrics providers: a "Dummy" provider that just outputs metrics to STDOUT for testing, and the Datadog provider.
Both current providers have been tested off of this branch and are functional. The process for adding new providers has been documented.
> Fixes #418 - Metrics Provider

- awslimitchecker/checker.py
- awslimitchecker/tests/test_checker.py
- awslimitchecker/trustedadvisor.py
This adds configuration for arn partitions and the TrustedAdvisor API region.  Certain regions, such as GocCloud, have a separate arn partition and/or support API region, requiring additional setup.
* I have the …
> GovCloud region support

- CHANGES.rst
- awslimitchecker/tests/test_trustedadvisor.py
- awslimitchecker/trustedadvisor.py
… on accounts that have TA but do not have the performance / Service Limits check
This was a minor logic bug in the ``_poll()`` method, where if the check couldn't be found the method would return ``(None, None)`` but the error handling code in the caller was looking for ``is None``.
> fixes #441 - unhandled exception during TA polling

- CHANGES.rst
- awslimitchecker/services/ec2.py
- awslimitchecker/tests/services/result_fixtures.py
- awslimitchecker/tests/services/test_ec2.py
This fixes a major error in the calculation. See #431, and specifically [this comment](https://github.com/jantman/awslimitchecker/issues/431#issuecomment-548599785), for the specifics. Put another way (from this code):
The value for each of ingress and egress is the count of all
PrefixListIds in all rules, plus the count of all
UserIdGroupPairs in all rules, plus the maximum of:
the count of all IpRanges in all rules
-or-
the count of all Ipv6Ranges in all rules
The limit that we alert on is the maximum of those values for
ingress and egress.
In short, behind the scenes, there are four firewall rulesets
per SG: (IPv4|IPv6) (ingress|egress)
Each can have a maximum of <limit> entries. PrefixListIds and
UserIdGroupPairs count towards both IPv4 and IPv6.
> Fixes #431 - fix major error in calculating 'EC2/Rules per VPC security group' limit

- awslimitchecker/services/ec2.py
Updates the default threshold for "Rules per Security Group" to 60 as per the "Inbound or outbound rules per security group" section [here](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html). …
> fixes #451: Updating default rules per VPC security group

- awslimitchecker/limit.py
There is a bug with division by zero:
```
awslimitchecker 8.0.1 is AGPL-licensed free software; all users have a right to the full source code of this version. See <https://github.com/jantman/awslimitchecker>
Traceback (most recent call last):
...
File "/awslimitchecker/limit.py", line 434, in check_thresholds
pct = (usage / (limit * 1.0)) * 100
ZeroDivisionError: float division by zero
```
* My contribution may perpetually be included in and …
> fix: avoid division by zero

- README.rst
This PR fixes the Python 2.7 end of support date in README.
Reference: 
- https://pythonclock.org/
> Fix Python 2.7 end of support date

- CHANGES.rst
- awslimitchecker/checker.py
- awslimitchecker/services/base.py
- awslimitchecker/services/ec2.py
- awslimitchecker/services/vpc.py
- awslimitchecker/tests/services/result_fixtures.py
- awslimitchecker/tests/services/test_base.py
- awslimitchecker/tests/services/test_vpc.py
- awslimitchecker/tests/test_checker.py
> Fixes #477 - ignore shared VPC resources and dedicated/host EC2 instances

- CHANGES.rst
- awslimitchecker/checker.py
- awslimitchecker/services/base.py
- awslimitchecker/services/ecs.py
- awslimitchecker/tests/services/test_base.py
- awslimitchecker/tests/services/test_ecs.py
- awslimitchecker/tests/support.py
- awslimitchecker/tests/test_checker.py
This PR fixes #463 
-   [Issue \#463][] - Updates for the major changes to ECS limits [in August 2020][]
-   The `EC2 Tasks per Service (desired count)` limit has been replaced with `Tasks per service`, which measures the desired count of tasks of all launch types (EC2 or Fargate). The default value of this limit has increased from 1000 to 2000.
-   The default of `Clusters` has increased from 2,000 to 10,000.
-   The default of `Services per Cluster` has increased from 1,000 to 2,000.
-   The `Fargate Tasks` limit has been removed.
-   The `Fargate On-Demand resource count` limit has been added, with a default quota value of 500. This limit measures the number of ECS tasks and EKS pods running concurrently on Fargate. The current usage for this metric is obtained from CloudWatch.
-   The …
> Fixes #463 - ECS and Fargate limit updates

- CHANGES.rst
- awslimitchecker/tests/test_trustedadvisor.py
- awslimitchecker/trustedadvisor.py
- docs/source/cli_usage.rst
- docs/source/cli_usage.rst.template
- docs/source/development.rst
- docs/source/getting_started.rst
- docs/source/internals.rst
- docs/source/python_usage.rst
This PR provides a temporary fix for #466 by disabling Trusted Advisor by default in regions/partitions other than China and GovCloud.
> Fixes #466 - Disable TA by default except in China and GovCloud

- CHANGES.rst
- awslimitchecker/quotas.py
- awslimitchecker/services/elb.py
- awslimitchecker/tests/services/test_elb.py
- awslimitchecker/tests/test_integration.py
This fixes #503 by handling the "Classic Load Balancers per Region" and "Application Load Balancers per Region" Service Quotas with Units set to either "Count" or "None". This bug was caused by yet another unannounced/undocumented change by AWS sometime between November 2 and November 9 of this year. See [this comment on the issue](https://github.com/jantman/awslimitchecker/issues/503#issuecomment-737226772) for details.
> Fix #503 - Handle (A|E)LB per Region Service Quota with units Count or None

- awslimitchecker/services/__init__.py
- awslimitchecker/services/kinesis.py
- awslimitchecker/tests/services/result_fixtures.py
- awslimitchecker/tests/services/test_kinesis.py
* Issue #495 - Adds support for Kinesis service. Only one limit/quota and related usage is supported initially: "Shards per Region" 
By submitting this work for inclusion in …
> issue #495 - Initial support for Kinesis service

- CHANGES.rst
- awslimitchecker/services/ec2.py
- awslimitchecker/tests/services/test_ec2.py
Fix multiple issues relating to VPC limits:
* Update the EC2 / ``Rules per VPC security group`` limit to support retrieving the current limit value from Service Quotas.
* Remove the ``EC2/Security groups per VPC`` limit, which no longer exists.
* Add the new ``EC2/VPC security groups per Region`` limit, with value retrieved from Service Quotas
> Fixes #498 - Fix VPC security group limits

- CHANGES.rst
- awslimitchecker/services/vpc.py
- awslimitchecker/tests/services/result_fixtures.py
- awslimitchecker/tests/services/test_vpc.py
This PR fixes #501 to update how the ``VPC/Network interfaces per Region`` limit is calculated.
Per https://docs.aws.amazon.com/vpc/latest/userguide/amazon-vpc-limits.html#vpc-limits-enis this limit is no longer calculated based on the on-demand instance count, but rather has a fixed default of 5000. This limit is also provided by Service Quotas, so in most cases the limit value will come from there.
> Fix #501 - update for new calculation of VPC/Network interfaces per Region limit

- awslimitchecker/services/elasticache.py
issue #488 - Update the following ElasticCache default limits: Nodes, Nodes per Cluster, Subnet Groups, Parameter Groups
By submitting this work for inclusion in awslimitchecker, I agree to …
> issue #488 - Update ElasticCache default limits

- awslimitchecker/services/ebs.py
- awslimitchecker/tests/services/result_fixtures.py
- awslimitchecker/tests/services/test_ebs.py
Add gp3 as an EBS volume type.
We are currently receiving an error: `ERROR - unknown volume type 'gp3' for volume ...`
[AWS docs](https://docs.aws.amazon.com/general/latest/gr/ebs-service.html) show these as two separate limits. Luckily, the limits appear to behave the same as the gp2 limits. …
> Add gp3 ebs type

- awslimitchecker/services/ecs.py
This PR adds fargate service quotas discovery (not the ECS service quotas as they aren't yet supported in the service quota API).
---
ask for assistance, or …
> add fargate service quotas

- awslimitchecker/services/ec2.py
- awslimitchecker/tests/services/test_ec2.py
This PR updates the security group counts to filter on owner by account id. In reference to https://github.com/jantman/awslimitchecker/issues/518
---
ask for …
> only query sgs owned by the account

- awslimitchecker/services/base.py
- awslimitchecker/tests/services/test_base.py
On occasions, see https://github.com/jantman/awslimitchecker/issues/512, the getmetricdata call can return no results as the metric data is not yet populated. This PR sets the query to query for the latest datapoint (max 1 datapoint) for now - 1 minute.
---
*Add a summary of what your PR does here. This could be as simple as "adds support for X service" or "fixes default limit for Y", or a longer explanation for less straightforward …
> query for now - 1 minute for cw metrics

- awslimitchecker/services/vpc.py
- awslimitchecker/tests/services/result_fixtures.py
- awslimitchecker/tests/services/test_vpc.py
Use max number of rules in each of egress, ingress, ipv4, ipv6 category for usage for `Rules per network ACL`.
By submitting this work for inclusion in awslimitchecker, I agree to the …
> issue 538 - Update usage calculation for Rules per network ACL

- awslimitchecker/connectable.py
- awslimitchecker/tests/test_connectable.py
- setup.cfg
This PR moves the boto config to using retry mode: standard, as the default retry mode is legacy.
https://boto3.amazonaws.com/v1/documentation/api/latest/guide/retries.html
Please let me know your thoughts on this PR.
---
writing tests for the …
> use retry mode: standard

- awslimitchecker/services/ec2.py
- awslimitchecker/tests/services/test_ec2.py
- docs/source/iam_policy.rst
- docs/source/limits.rst
BREAKING CHANGE
As mentioned in issue #502, the limit "Max spot instance requests per region" was removed from AWS and replaced by the following limits, based on the number of vCPU:
- All F Spot Instance Requests
- All G Spot Instance Requests
- All Inf Spot Instance Requests
- All P Spot Instance Requests
- All Standard (A, C, D, H, I, M, R, T, Z) Spot Instance Requests
- All X Spot Instance Requests
As a result, the usage reported by awslimitchecker is not relevant anymore.
In order to fix this, this commit replaces the call to the EC2 API describe_spot_instance_requests() with a call to the CloudWatch API, since the usage of Spot requests vCPUs is now available as a metric in CloudWatch.
In addition, the applied limits are now retrieved from the Service Quotas service.
writing tests …
> Replace "Max spot instance requests per region" limit with vCPU-based limits

- awslimitchecker/services/__init__.py
- awslimitchecker/services/certificatemanager.py
- awslimitchecker/tests/services/result_fixtures.py
- awslimitchecker/tests/services/test_certificatemanager.py
- docs/source/awslimitchecker.services.certificatemanager.rst
- docs/source/awslimitchecker.services.rst
- docs/source/iam_policy.rst
Relates to #540
Add support for the Certificate Manager service (ACM)
Only the quota "Number of ACM certificates" is checked.
Added unit tests.
Here are the Quotas for the ACM service, as specified in the documentation
(https://docs.aws.amazon.com/acm/latest/userguide/acm-limits.html)
> **Number of ACM certificates**
> (default: 1000)
> New AWS accounts may start with a quota lower than the maximum. Expired and revoked certificates …
> Support CertificateManager service
