docs/examples/Jenkins-AWS_Limit_Check.xml, docs/examples/README.rst, docs/examples/check_aws_limits.py, docs/examples/test_check_aws_limits.py, docs/source/python_usage.rst
This is only docs/examples, no need to cut a new release for it.
Note that pytest is breaking for py26 due to https://github.com/pytest-dev/pytest/issues/1035
=> add an example wrapper script with output colorization, and a sample Jenkins job

CHANGES.rst, awslimitchecker/tests/test_versioncheck.py
=> Fixes #47 - explicit git fetch --tags in versioncheck git tests

.travis.yml, CHANGES.rst, awslimitchecker/version.py, docs/source/development.rst, integration_helper.sh, tox.ini
=> Issue #104 - release 0.2.2

awslimitchecker/services/autoscaling.py, awslimitchecker/services/base.py, awslimitchecker/services/ebs.py, awslimitchecker/services/ec2.py, awslimitchecker/services/elasticache.py, awslimitchecker/services/elb.py, awslimitchecker/services/newservice.py.example, awslimitchecker/services/rds.py, awslimitchecker/services/vpc.py, awslimitchecker/tests/services/test_autoscaling.py, awslimitchecker/tests/services/test_ebs.py, awslimitchecker/tests/services/test_ec2.py, awslimitchecker/tests/services/test_elb.py, awslimitchecker/tests/services/test_newservice.py.example, awslimitchecker/tests/services/test_vpc.py, awslimitchecker/tests/test_trustedadvisor.py, awslimitchecker/tests/test_utils.py, awslimitchecker/trustedadvisor.py, awslimitchecker/utils.py, docs/source/development.rst, docs/source/internals.rst
and use paginate_dict() directly where needed
=> Issues/120 - remove boto_query_wrapper() and paginate_query()

CHANGES.rst, README.rst, docs/source/conf.py, docs/source/index.rst, setup.py, tox.ini
Minor update to project description in docs and setup.py; use only _VERSION (not git) when building in RTD; include short description in docs HTML title; set meta description on docs index.rst
=> Issues/134 - doc fixes

CHANGES.rst, awslimitchecker/tests/support.py, awslimitchecker/tests/test_integration.py, awslimitchecker/tests/test_trustedadvisor.py, awslimitchecker/trustedadvisor.py
Fix to prevent duplicate TrustedAdvisor polling, and integration test to confirm.
=> Issues/157 - prevent duplicate TrustedAdvisor polling

CHANGES.rst, awslimitchecker/services/__init__.py, awslimitchecker/services/iam.py, awslimitchecker/tests/services/result_fixtures.py, awslimitchecker/tests/services/test_iam.py, awslimitchecker/tests/test_integration.py, docs/source/awslimitchecker.services.iam.rst, docs/source/awslimitchecker.services.rst, docs/source/iam_policy.rst, docs/source/limits.rst
using the GetAccountSummary API action for both limits and usage
=> fixes #50 - add support for a subset of IAM limits

CHANGES.rst, awslimitchecker/services/__init__.py, awslimitchecker/services/addservice, awslimitchecker/services/s3.py, awslimitchecker/tests/services/test_newservice.py.example, awslimitchecker/tests/services/test_s3.py, docs/source/awslimitchecker.services.rst, docs/source/awslimitchecker.services.s3.rst, docs/source/cli_usage.rst, docs/source/iam_policy.rst, docs/source/limits.rst
Support for checking S3 Buckets limit.
=> Issues/48 - support for S3

CHANGES.rst, awslimitchecker/services/__init__.py, awslimitchecker/services/cloudformation.py, awslimitchecker/tests/services/test_cloudformation.py, docs/source/awslimitchecker.services.cloudformation.rst, docs/source/awslimitchecker.services.rst, docs/source/cli_usage.rst, docs/source/iam_policy.rst, docs/source/limits.rst
=> fixes #69 - add support for CloudFormation service, Stacks limit

CHANGES.rst, awslimitchecker/services/ses.py, awslimitchecker/tests/services/test_ses.py, awslimitchecker/version.py
=> fixes #170 and bump to 0.4.0 - emergency fix for SES unavailable region bug

awslimitchecker/services/ebs.py, awslimitchecker/tests/services/result_fixtures.py, awslimitchecker/tests/services/test_ebs.py
=> issue#189 Added support for 2 new EBS volume types 'st1' and 'sc1'

CHANGES.rst, awslimitchecker/services/ebs.py, awslimitchecker/tests/services/result_fixtures.py, awslimitchecker/tests/services/test_ebs.py, awslimitchecker/version.py, docs/source/cli_usage.rst, docs/source/conf.py, tox.ini
__IMPORTANT:__ Please take note of the below checklist, especially the first two items.
the issue is …
=> Release 0.4.4

CHANGES.rst, awslimitchecker/limit.py, awslimitchecker/tests/test_limit.py, awslimitchecker/tests/test_trustedadvisor.py, awslimitchecker/trustedadvisor.py, awslimitchecker/version.py, docs/source/cli_usage.rst, docs/source/cli_usage.rst.template, docs/source/development.rst, docs/source/limits.rst
=> Release 0.5.0

awslimitchecker/services/vpc.py, awslimitchecker/tests/services/result_fixtures.py, awslimitchecker/tests/services/test_vpc.py, docs/source/limits.rst
This pull request implements a limit check for NAT gateways.
I reviewed the code guidelines, rebuilt the docs after changing it, wrote tests for the new feature, and this PR includes the Contributor License Agreement. Please let me know if anything else is necessary.
---
__IMPORTANT:__ Please take note of the below checklist, especially the first two items. …
=> Implement NAT gateways

CHANGES.rst, awslimitchecker/connectable.py, awslimitchecker/tests/test_connectable.py
This is a minor rework of PR #222.
=> Fixes #221 - Rework of PR #222

CHANGES.rst, awslimitchecker/checker.py, awslimitchecker/connectable.py, awslimitchecker/runner.py, awslimitchecker/services/base.py, awslimitchecker/tests/services/test_base.py, awslimitchecker/tests/support.py, awslimitchecker/tests/test_checker.py, awslimitchecker/tests/test_connectable.py, awslimitchecker/tests/test_runner.py, awslimitchecker/trustedadvisor.py, docs/source/cli_usage.rst, docs/source/getting_started.rst
This fixes up PR #188 and fixes #213
=> PR #188 fixup

CHANGES.rst, awslimitchecker/services/ec2.py, awslimitchecker/tests/services/test_ec2.py
=> fixes #231 - add support for new f1, r4 and t2.(xlarge|2xlarge) instance types

CHANGES.rst, awslimitchecker/tests/conftest.py, awslimitchecker/tests/services/test_base.py, awslimitchecker/tests/test_integration.py
This implementation uses ``pytest_generate_tests`` - http://doc.pytest.org/en/latest/parametrize.html
=> fixes #233 - replace yield tests with parametrize

CHANGES.rst, README.rst, awslimitchecker/checker.py, awslimitchecker/runner.py, awslimitchecker/tests/test_checker.py, awslimitchecker/tests/test_runner.py, awslimitchecker/tests/test_trustedadvisor.py, awslimitchecker/trustedadvisor.py, docs/source/cli_usage.rst, docs/source/conf.py, docs/source/development.rst, docs/source/getting_started.rst, docs/source/iam_policy.rst, docs/source/internals.rst, docs/source/python_usage.rst, setup.py, tox.ini
See extensive docs within this PR.
=> Fixes #239 - add capability to refresh TA checks

.travis.yml, CHANGES.rst, tox.ini
=> Travis fixes

CHANGES.rst, README.rst, awslimitchecker/services/elasticache.py, awslimitchecker/tests/services/result_fixtures.py, awslimitchecker/tests/services/test_elasticache.py, awslimitchecker/version.py, dev/release.py, dev/requirements_dev.txt, dev/terraform.py, docs/source/cli_usage.rst, docs/source/development.rst, docs/source/getting_help.rst, docs/source/limits.rst, setup.py
0.10.0 release
Once merged, continue at [#13 on the release checklist](http://awslimitchecker.readthedocs.io/en/develop/development.html#release-checklist)
=> Release 0.10.0

CHANGES.rst, docs/source/development.rst, docs/source/getting_started.rst
Documents our versioning policy, and makes recommendations for specifying version requirements.
=> Fixes #254 - document versioning policy

CHANGES.rst, README.rst, awslimitchecker/services/elb.py, awslimitchecker/tests/services/test_elb.py, docs/source/getting_started.rst, setup.py
This finally pushes out the fix for #293
=> Issues/293 - Increase retry limit for elbv2 API calls and bump botocore/boto3 req

CHANGES.rst, awslimitchecker/services/ebs.py, awslimitchecker/tests/services/test_ebs.py, awslimitchecker/version.py
=> fixes #341 - handle Trusted Advisor EBS check renames, and bump version to 4.0.2

CHANGES.rst, awslimitchecker/services/ebs.py, awslimitchecker/tests/services/test_ebs.py, awslimitchecker/version.py
=> fixes #343 - 4.0.2 release

awslimitchecker/services/firehose.py, docs/source/limits.rst
Changed Firehose/Delivery streams per region limit value default to 50 (from 20). According to docs here https://docs.aws.amazon.com/firehose/latest/dev/limits.html.
- [na] Complete, correctly-formatted documentation for all classes, functions and methods.
- [na] Connections to the AWS services should only be made by the class's
- [na] All modules should have (and use) …
=> Changed Firehose/Delivery streams per region limit value to 50 (from 20)

docs/source/development.rst
Fix minor typo.
include complete test coverage will usually be merged …
=> Fix minor typo

CHANGES.rst, awslimitchecker/services/vpc.py, awslimitchecker/tests/services/result_fixtures.py, awslimitchecker/tests/services/test_vpc.py, awslimitchecker/version.py, docs/source/cli_usage.rst, docs/source/development.rst, docs/source/limits.rst
=> fixes #380 - 6.1.0 release

awslimitchecker/services/ses.py
Handle AccessDenied exception in SES check for non-supported region
More info and stacktrace output on the issue : https://github.com/jantman/awslimitchecker/issues/382
* I have the legal power and rights to …
=> Bugfix for handling AccessDenied exception in SES check #382

CHANGES.rst, awslimitchecker/services/ses.py, awslimitchecker/tests/services/test_ses.py, awslimitchecker/version.py
=> fixes #385 - 6.1.1 release

CHANGES.rst, awslimitchecker/services/vpc.py, awslimitchecker/tests/services/result_fixtures.py, awslimitchecker/version.py
=> fixes #388 - 6.1.2 release

CHANGES.rst, awslimitchecker/services/vpc.py, awslimitchecker/tests/services/test_vpc.py, awslimitchecker/version.py
=> fixes #395 - 6.1.4 release

CHANGES.rst, awslimitchecker/services/ses.py, awslimitchecker/tests/services/test_ses.py, awslimitchecker/version.py
=> fixes #398 - 6.1.5 release

CHANGES.rst, awslimitchecker/runner.py, awslimitchecker/tests/test_runner.py, awslimitchecker/version.py, docs/source/cli_usage.rst, docs/source/cli_usage.rst.template
=> fixes #404 - 6.1.6 release

CHANGES.rst, awslimitchecker/tests/test_trustedadvisor.py, awslimitchecker/trustedadvisor.py, awslimitchecker/version.py
Fixes #406, an unhandled exception when a Trusted Advisor check has a null timestamp.
* The …
=> Fixes #406 - unhandled exception when TA check has null timestamp

CHANGES.rst, awslimitchecker/tests/test_trustedadvisor.py, awslimitchecker/trustedadvisor.py, awslimitchecker/version.py
=> fixes #408 - 6.1.7 release

CHANGES.rst, docs/source/limits.rst
=> fixes #410 - missing TA info on Limits page of docs

CHANGES.rst, awslimitchecker/services/elb.py, awslimitchecker/tests/services/test_elb.py, awslimitchecker/tests/test_utils.py, awslimitchecker/version.py, docs/examples/check_aws_limits.py, docs/examples/multi-region_multi-account/config/111111111111/us-east-1/limit_overrides.json, docs/source/cli_usage.rst, docs/source/development.rst, docs/source/limits.rst
=> fixes #415 - 7.0.0 release

CHANGES.rst, awslimitchecker/services/cloudtrail.py, awslimitchecker/tests/services/result_fixtures.py, awslimitchecker/tests/services/test_cloudtrail.py
Fixes #439 - see [issue comment](https://github.com/jantman/awslimitchecker/issues/439#issuecomment-548162769) for details.
=> Fixes #439 - unhanelded exception when organization CloudTrail trails are present

CHANGES.rst, awslimitchecker/checker.py, awslimitchecker/connectable.py, awslimitchecker/tests/test_connectable.py, docs/source/cli_usage.rst, docs/source/cli_usage.rst.template, docs/source/python_usage.rst
This allows overriding max retries on a per-API basis via environment variables. See the changelog for details.
=> Fixes #435 - better handling of Throttling

CHANGES.rst, awslimitchecker/limit.py, awslimitchecker/tests/conftest.py, awslimitchecker/tests/test_limit.py, awslimitchecker/version.py
=> fixes #461 - 8.0.2 release

CHANGES.rst, awslimitchecker/services/ses.py, awslimitchecker/tests/conftest.py, awslimitchecker/tests/services/test_ses.py
=> Fixes #464 - handle ConnectTimeoutError from SES in regions where it is not enabled

.gitignore, CHANGES.rst, README.rst, dev/release.py, dev/release_utils.py, dev/requirements_dev.txt
Move CI builds from travis-ci.org to travis-ci.com
=> Move CI builds from travis-ci.org to travis-ci.com

awslimitchecker/services/__init__.py, awslimitchecker/services/eks.py, awslimitchecker/tests/services/result_fixtures.py, awslimitchecker/tests/services/test_eks.py
issue #472 - Add support for AWS EKS services.
All limits also provide usage - except "Nodes per managed node group", which I've not found a way to grab usage
By submitting this work for …
=> issue #472 - Add support for AWS EKS service

awslimitchecker/services/vpc.py
Add a quota_name  the `Entries per route table` quota which maps to the AWS quota `Routes per route table` …
=> feat(vpc.py): add quota_name for Entries per route table.

awslimitchecker/services/ec2.py, awslimitchecker/tests/services/test_ec2.py
This PR updates the quota names for EIPs, in reference to: https://github.com/jantman/awslimitchecker/issues/527
---
ask for assistance, or clarify that you'd like …
=> update quota names for EIPs

awslimitchecker/services/ebs.py
This PR updates the EBS service quota names, in reference to: https://github.com/jantman/awslimitchecker/issues/521 with respect to service quotas (not TA).
--- …
=> update service quota names for ebs

awslimitchecker/services/ec2.py, awslimitchecker/tests/services/test_ec2.py
This fixes a minor parameter bug in #535 that showed up in the integration tests.
=> PR #535 fix
